### PR TITLE
fix: import mnemonic from advanced setup does not set ldk backend type

### PR DESCRIPTION
**Pull request by rolznz**
Fixes https://github.com/getAlby/hub/issues/636

### CODE REVIEW

**Review by im-adithya — COMMENTED** [review]
Can't we just add this in [here](https://github.com/getAlby/hub/blob/master/frontend/src/screens/setup/SetupPassword.tsx#L47) instead of importing things again?
```
store.updateNodeInfo({
  backendType: "LDK",
});
```

**Comment by rolznz** [comment]
> Can't we just add this in [here](https://github.com/getAlby/hub/blob/master/frontend/src/screens/setup/SetupPassword.tsx#L47) instead of importing things again?
> 
> ```
> store.updateNodeInfo({
>   backendType: "LDK",
> });
> ```

@im-adithya I think you're right, that code is also only executed for LDK. Thanks!

**Comment by alekqss** [comment]
I had this problem with ‘Import Existing Mnemonic’..
After a couple of tries I saw the "Connect you Alby account (Request authorization code)" screen
request-auth-code

After doing so I could access to my new Alby Hub, but savings balance is 0 (and it shouldn't) so I checked the recovery phrase and it is different than my original one...

It's a bit weird because the email address and lightning address of the new Alby Hub are the same than the old one ...

Should I simply send the funds in the Savings balance from my old Alby Hub to the new one? 

Or, in case this is fixed in v.1.8.0, should I repeat the ‘Import Existing Mnemonic’ process again?

**Comment by rolznz** [comment]
@alekqss can you try again in 1.8.0? you will have to delete the alby hub working directory so that you can go through the onboarding again. To know where the working directory is, it should be logged to the console on startup.

**Pull request merged**
