### PR TITLE
fix: update app store images

### LINKED ISSUE #569: App store images need to be redone as square images without transparency
image

This results in issues in the transaction list:

image

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #569 

@rolznz can you please help me with the Zap Planner logo? All others are square now, except Paper-Scissors-HODL and Lume

## Screenshot

Screenshot 2024-08-30 at 2 59 25 PM
Screenshot 2024-08-30 at 3 00 06 PM

### CODE REVIEW

**Comment by rolznz** [comment]
@im-adithya awesome! I think it'd be nice to add a bg for Habla news and fix the Lume 

It seems to be 
image

**Comment by im-adithya** [comment]
Changed, I got the lume icon from here: https://github.com/lumehq/lume/blob/main/src-tauri/icons/Square284x284Logo.png

They seem to have updated it very recently

**Comment by im-adithya** [comment]
Ready to merge

**Review by rolznz — APPROVED** [review]
utACK

**Comment by rolznz** [comment]
Thanks Adithya!

**Pull request merged**
