### PR TITLE
feat: support limit and offset in list transactions

### PR DESCRIPTION
**Pull request by im-adithya**
- Adds support for `limit` and `offset` parameters
- Also adds the transaction hint in the Onboardsing Checklist

Screenshot 2024-07-04 at 6 03 00 PM

### CODE REVIEW

**Comment by im-adithya** [comment]
See https://github.com/getAlby/nostr-wallet-connect-next/pull/572 for more info

**Comment by rolznz** [comment]
@im-adithya should we wait for the dynamic budgets / internal transactions PR to be merged then? because if we add this code but it is not used on the frontend, it seems wrong to me

**Comment by im-adithya** [comment]
Hmmm, the reason why I added this is because we need only one transaction to check the transaction item in the list, so there I'm using the limit, if you think this causes many conflicts in dynamic budgets, I can close, upto you 👍

**Review by rolznz — APPROVED** [review]
tACK

**Comment by rolznz** [comment]
@im-adithya ah, I see. Thanks!

**Comment by rolznz** [comment]
@im-adithya we could do even better by also supporting the type param (See https://github.com/nostr-protocol/nips/blob/master/47.md#list_transactions) and then we can have checklist items for both sending and receiving by getting the first incoming and outgoing transactions

**Pull request merged**
