### PR TITLE
feat: add back button in setup screen

### LINKED ISSUE #310: Add back button in Wails app
There's no browser navigation so it's impossible to go back

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #310 

## Screenshot
Screenshot 2024-07-25 at 7 23 03 PM

### CODE REVIEW

**Comment by rolznz** [comment]
@im-adithya this is for Wails/Desktop mode where it has no browser navigation, so shouldn't we always have a back button in that case?

Therefore, it also doesn't need to be shown in non-desktop mode

**Comment by rolznz** [comment]
@im-adithya sounds good and fixes the main issue. But I think we should whitelist, not blacklist pages since you missed some:

image

**Comment by rolznz** [comment]
@im-adithya I pushed a fix, can you check it?

**Review by rolznz — APPROVED** [review]
tACK

**Comment by im-adithya** [comment]
> I pushed a fix, can you check it?

Looks better now, thanks!

**Pull request merged**
