### PR TITLE
feat: add uncle jim internal app

### PR DESCRIPTION
**Pull request by rolznz**
Closes https://github.com/getAlby/hub/issues/489

Fixes some other issues:
- Gives isolated apps get_info permission (recommended by Bumi to reduce complexity)
- Removes duplicated toasts
- Adds loading button for app creation

TODOs:
- [x] app metadata?
- [x] update app icon
- [x] update app store card button icon?
- [ ] PoS app https://github.com/getAlby/hub/pull/580

Updated screenshots: 

image

image

Video: https://www.loom.com/share/81dc03e041fc49d2ad54acb219511638

### CODE REVIEW

**Comment by MoritzKa** [comment]
Love it!!!

- ...powered by your **H**ub
- Does it actually contain a link, that Time just needs to click on to connect the wallet to the Alby Account or only the connection secret?

**Comment by bumi** [comment]
we need to explain there what happens and what people can do there and why. 

people come to that page without prior knowledge, so we need to pick them up and guide them through this flow. 
what do they want to achieve?

**Comment by rolznz** [comment]
@MoritzKa 

> Does it actually contain a link, that Time just needs to click on to connect the wallet to the Alby Account or only the connection secret?

Yes, the link is a special getalby.com link which will automatically attach the wallet to your account. But you must be logged in for it to work

**Comment by rolznz** [comment]
Updated copy & screenshots

**Review by reneaaron — APPROVED** [review]
Great job! :100: 

tACK

**Comment by rolznz** [comment]
@reneaaron thanks for the improvements!

**Pull request merged**
